= Python Up-skilling

Within the *Python up-skilling* program we work towards the completion of a
given *challenge* (ex: _parse big JSON file_), to acquire new knowledge. We do
this by *defining* required *concepts* to know for solvability, *provide
material* to learn and finally by *solving the problem*.

This repository acts as *storage of potential modules* likely to appear during
the challenges we will receive, in the same manner as the _Syllabus Becodus_.


== Modules

[%header,cols="^2,7"]
|===
| Module | Description

| link:https://github.com/becodeorg/Python-Upskilling/tree/master/fundamentals[fundamentals]
| Module focusing on quickly acquiring the fundamentals.

| link:https://github.com/becodeorg/Python-Upskilling/tree/master/I-O[I/O]
| Module focusing on input and output from all different types of sources.

|===

NOTE: Try to implement *good practices* (_PEP8_, _..._) in each module so that
they can be transmitted as seamlessly as possible.


== Useful links

* https://docs.python.org/3/[documentation]
